// frontend/src/components/NodeTypes/AgentNode.tsx
import React, { useState, useCallback, useRef } from 'react';
import { Handle, Position } from 'reactflow';
import './NodeStyles.css';

interface AgentNodeProps {
  data: {
    name: string;
    userPrompt?: string;
    status?: string;
    result?: string;
    onUpdate: (updates: any) => void;
    onRename?: (newName: string) => void;
  };
}

const AgentNode: React.FC<AgentNodeProps> = ({ data }) => {
  const [isExpanded, setIsExpanded] = useState(false);
  const [isEditingName, setIsEditingName] = useState(false);
  const [prompt, setPrompt] = useState(data.userPrompt || '');
  const [name, setName] = useState(data.name);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  
  const getStatusColor = () => {
    switch (data.status) {
      case 'running': return '#ffa500';
      case 'completed': return '#00ff00';
      case 'failed': return '#ff0000';
      default: return '#888';
    }
  };
  
  const handleNameDoubleClick = () => {
    setIsEditingName(true);
  };
  
  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setName(e.target.value);
  };
  
  const handleNameBlur = () => {
    if (name.trim() && data.onRename) {
      data.onRename(name.trim());
    } else {
      setName(data.name);
    }
    setIsEditingName(false);
  };
  
  const handlePromptChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newValue = e.target.value;
    setPrompt(newValue);
    data.onUpdate({ userPrompt: newValue });
  }, [data.onUpdate]);
  
  // Полностью останавливаем все события мыши на textarea
  const handleTextareaMouseDown = (e: React.MouseEvent) => {
    e.stopPropagation();
    e.preventDefault();
    // Фокус на textarea после остановки события
    setTimeout(() => {
      textareaRef.current?.focus();
    }, 0);
  };
  
  const handleTextareaMouseUp = (e: React.MouseEvent) => {
    e.stopPropagation();
  };
  
  const handleTextareaClick = (e: React.MouseEvent) => {
    e.stopPropagation();
  };
  
  const handleExpandClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    setIsExpanded(!isExpanded);
  };
  
  return (
    <div className="node agent-node" style={{ borderColor: getStatusColor() }}>
      <Handle type="target" position={Position.Top} />
      <div className="node-header">
        <span className="node-icon">🤖</span>
        {isEditingName ? (
          <input
            type="text"
            value={name}
            onChange={handleNameChange}
            onBlur={handleNameBlur}
            onKeyDown={(e) => e.key === 'Enter' && handleNameBlur()}
            onMouseDown={(e) => e.stopPropagation()}
            autoFocus
            className="node-name-input"
          />
        ) : (
          <span className="node-name" onDoubleClick={handleNameDoubleClick}>
            {data.name}
          </span>
        )}
        <span className="node-status" style={{ background: getStatusColor() }} />
        <button 
          className="node-expand" 
          onClick={handleExpandClick}
          onMouseDown={(e) => e.stopPropagation()}
        >
          {isExpanded ? '▼' : '▶'}
        </button>
      </div>
      
      {isExpanded && (
        <div className="node-content">
          <textarea
            ref={textareaRef}
            value={prompt}
            onChange={handlePromptChange}
            onMouseDown={handleTextareaMouseDown}
            onMouseUp={handleTextareaMouseUp}
            onClick={handleTextareaClick}
            placeholder="Введите промпт для агента..."
            rows={5}
            style={{ 
              width: '100%', 
              resize: 'vertical',
              userSelect: 'text',
              cursor: 'text'
            }}
          />
          {data.result && (
            <div className="node-result">
              <strong>Результат:</strong>
              <div>{data.result}</div>
            </div>
          )}
        </div>
      )}
      
      <Handle type="source" position={Position.Bottom} />
    </div>
  );
};

export default AgentNode;

// frontend/src/components/nodes/AgentNode.vue
<template>
  <div class="node agent-node" :class="{ selected: isSelected }" :style="{ borderColor: statusColor, position: 'relative' }">
    <button 
      v-if="isSelected" 
      class="delete-btn" 
      @click.stop="handleDelete"
      title="Удалить узел"
    >
      ✕
    </button>
    <Handle type="target" :position="Position.Top" />
    <div class="node-header">
      <span class="node-icon">🤖</span>
      <span 
        v-if="!editingName" 
        class="node-name" 
        @dblclick="startEditName"
      >
        {{ props.data.name }}
      </span>
      <input
        v-else
        ref="nameInput"
        v-model="localName"
        class="node-name-input"
        @blur="finishEditName"
        @keyup.enter="finishEditName"
      />
      <span class="node-status" :style="{ background: statusColor }"></span>
      <button class="node-expand" @click="toggleExpand">
        {{ expanded ? '▼' : '▶' }}
      </button>
    </div>
    
    <div v-if="expanded" class="node-content">
      <textarea
        v-model="localPrompt"
        placeholder="Введите промпт для агента..."
        rows="5"
        @mousedown.stop
        @mouseup.stop
      />
      <div v-if="props.data.result" class="node-result">
        <strong>Результат:</strong>
        <div>{{ props.data.result }}</div>
      </div>
    </div>
    
    <Handle type="source" :position="Position.Bottom" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, nextTick } from 'vue';
import { Handle, Position } from '@vue-flow/core';

const props = defineProps<{
  id: string;
  selected?: boolean;
  data: {
    name: string;
    userPrompt?: string;
    status?: string;
    result?: string;
    onUpdate?: (updates: any) => void;
    onRename?: (name: string) => void;
    onDelete?: () => void;
  };
}>();

const emit = defineEmits<{
  (e: 'delete'): void;
}>();

const expanded = ref(false);
const editingName = ref(false);
const localName = ref(props.data.name);
const localPrompt = ref(props.data.userPrompt || '');
const nameInput = ref<HTMLInputElement | null>(null);

const isSelected = computed(() => props.selected === true);
const statusColor = computed(() => {
  switch (props.data.status) {
    case 'running': return '#ffa500';
    case 'completed': return '#00ff00';
    case 'failed': return '#ff0000';
    default: return '#888';
  }
});

watch(localPrompt, (newVal) => {
  if (props.data.onUpdate) {
    props.data.onUpdate({ userPrompt: newVal });
  }
});

function toggleExpand() {
  expanded.value = !expanded.value;
}

function startEditName() {
  editingName.value = true;
  nextTick(() => {
    nameInput.value?.focus();
  });
}

function finishEditName() {
  if (localName.value.trim() && props.data.onRename) {
    props.data.onRename(localName.value.trim());
  } else {
    localName.value = props.data.name;
  }
  editingName.value = false;
}

function handleDelete() {
  if (props.data.onDelete) {
    props.data.onDelete();
  } else {
    emit('delete');
  }
}
</script>

<style scoped>
.node {
  background: #2d2d44;
  border-radius: 8px;
  border: 2px solid #4a4a6a;
  min-width: 200px;
  max-width: 300px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.3);
  position: relative;
}
.agent-node {
  border-color: #6c63ff;
}
.agent-node.selected {
  border-color: #ff6b6b;
  box-shadow: 0 0 0 2px rgba(255,107,107,0.3);
}
.delete-btn {
  position: absolute;
  top: -10px;
  right: -10px;
  width: 24px;
  height: 24px;
  background: #dc3545;
  color: white;
  border: none;
  border-radius: 50%;
  cursor: pointer;
  font-size: 14px;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10;
  transition: all 0.2s;
}
.delete-btn:hover {
  background: #c82333;
  transform: scale(1.1);
}
.node-header {
  padding: 10px;
  background: #1e1e2e;
  border-radius: 6px 6px 0 0;
  display: flex;
  align-items: center;
  gap: 8px;
}
.node-icon {
  font-size: 20px;
}
.node-name {
  flex: 1;
  font-weight: bold;
  color: #eee;
  cursor: pointer;
}
.node-name-input {
  flex: 1;
  background: #1a1a2e;
  border: 1px solid #6c63ff;
  color: #eee;
  border-radius: 4px;
  padding: 2px 6px;
  font-size: 14px;
  font-weight: bold;
}
.node-status {
  width: 10px;
  height: 10px;
  border-radius: 50%;
}
.node-expand {
  background: none;
  border: none;
  color: #eee;
  cursor: pointer;
  font-size: 12px;
}
.node-content {
  padding: 10px;
}
.node-content textarea {
  width: 100%;
  background: #1a1a2e;
  border: 1px solid #4a4a6a;
  color: #eee;
  border-radius: 4px;
  padding: 8px;
  font-family: monospace;
  resize: vertical;
}
.node-result {
  margin-top: 10px;
  padding: 8px;
  background: #1a1a2e;
  border-radius: 4px;
  font-size: 12px;
  word-break: break-word;
}
</style>
